Repository FESI5-team9/backend, pull requests merged in 2024-12, with the labels that each got.

#24 dev merge 후 access token, refresh token 비즈니스 로직 변경
  src/main/java/com/fesi/mukitlist/api/controller/auth/AuthenticationController.java
  src/main/java/com/fesi/mukitlist/api/controller/auth/UserController.java
  src/main/java/com/fesi/mukitlist/api/controller/auth/request/TokenRequest.java
  src/main/java/com/fesi/mukitlist/api/controller/auth/response/AuthenticationResponse.java
  src/main/java/com/fesi/mukitlist/api/repository/TokenRepository.java
  src/main/java/com/fesi/mukitlist/api/service/auth/AuthenticationService.java
  src/main/java/com/fesi/mukitlist/api/service/auth/JwtService.java
  src/main/java/com/fesi/mukitlist/api/service/auth/request/TokenServiceRequest.java
  src/main/java/com/fesi/mukitlist/config/ApplicationConfig.java
  src/main/java/com/fesi/mukitlist/config/JwtAuthenticationFilter.java
  src/main/java/com/fesi/mukitlist/domain/auth/Token.java
  src/main/resources/application.yml
  src/test/java/com/fesi/mukitlist/MukitlistApplicationTests.java
Labels: enhancement

#28 refresh token 500 ERROR 수정
  src/main/java/com/fesi/mukitlist/api/repository/TokenRepository.java
  src/main/java/com/fesi/mukitlist/api/service/auth/AuthenticationService.java
Labels: fix

#31 fix : #27 - 수정 반영 분 누락 적용
  src/main/java/com/fesi/mukitlist/api/controller/gathering/GatheringController.java
  src/main/java/com/fesi/mukitlist/api/controller/gathering/request/GatheringCreateRequest.java
  src/main/java/com/fesi/mukitlist/api/service/gathering/GatheringService.java
  src/main/java/com/fesi/mukitlist/api/service/gathering/request/GatheringServiceCreateRequest.java
  src/main/java/com/fesi/mukitlist/api/service/gathering/response/GatheringWithParticipantsResponse.java
  src/main/java/com/fesi/mukitlist/domain/gathering/Gathering.java
  src/main/java/com/fesi/mukitlist/global/annotation/CustomAuthenticationPrincipalResolver.java
Labels: documentation, enhancement

#33 카카오 소셜 로그인
  .gitignore
  build.gradle
  src/main/java/com/fesi/mukitlist/api/controller/auth/AuthenticationController.java
  src/main/java/com/fesi/mukitlist/api/controller/auth/request/TokenRequest.java
  src/main/java/com/fesi/mukitlist/api/controller/auth/request/UserCreateRequest.java
  src/main/java/com/fesi/mukitlist/api/controller/auth/response/AuthenticationResponse.java
  src/main/java/com/fesi/mukitlist/api/controller/oauth/kakao/KakaoTokenController.java
  src/main/java/com/fesi/mukitlist/api/controller/oauth/kakao/client/KakaoTokenClient.java
  src/main/java/com/fesi/mukitlist/api/controller/oauth/kakao/request/KakaoTokenRequest.java
  src/main/java/com/fesi/mukitlist/api/controller/oauth/kakao/response/KakaoTokenResponse.java
  src/main/java/com/fesi/mukitlist/api/exception/ExceptionCode.java
  src/main/java/com/fesi/mukitlist/api/exception/FeignClientExceptionErrorDecoder.java
  src/main/java/com/fesi/mukitlist/api/repository/TokenRepository.java
  src/main/java/com/fesi/mukitlist/api/repository/UserRepository.java
  src/main/java/com/fesi/mukitlist/api/service/auth/AuthenticationService.java
  src/main/java/com/fesi/mukitlist/api/service/auth/JwtService.java
  src/main/java/com/fesi/mukitlist/api/service/auth/UserService.java
  src/main/java/com/fesi/mukitlist/api/service/auth/request/TokenServiceRequest.java
  src/main/java/com/fesi/mukitlist/api/service/auth/request/UserServiceCreateRequest.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/PrincipalOauthUserService.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/PrincipalService.java
  src/main/java/com/fesi/mukitlist/config/ApplicationConfig.java
  src/main/java/com/fesi/mukitlist/config/FeignConfig.java
  src/main/java/com/fesi/mukitlist/config/JwtAuthenticationFilter.java
  src/main/java/com/fesi/mukitlist/config/SecurityConfig.java
  src/main/java/com/fesi/mukitlist/config/WebConfig.java
  src/main/java/com/fesi/mukitlist/domain/auth/PrincipalDetails.java
  src/main/java/com/fesi/mukitlist/domain/auth/Token.java
  src/main/java/com/fesi/mukitlist/domain/auth/TokenType.java
  src/main/java/com/fesi/mukitlist/domain/auth/User.java
  src/main/java/com/fesi/mukitlist/domain/auth/constant/GrantType.java
  src/main/java/com/fesi/mukitlist/domain/auth/constant/TokenType.java
  src/main/java/com/fesi/mukitlist/domain/oauth/KakaoUserInfo.java
  src/main/java/com/fesi/mukitlist/domain/oauth/OAuth2UserInfo.java
  src/main/resources/application.yml
  src/test/java/com/fesi/mukitlist/api/repository/UserGatheringRepositoryTest.java
Labels: documentation, enhancement

#35 kakao social login access token 비즈니스 로직 수정
  src/main/java/com/fesi/mukitlist/api/controller/auth/AuthenticationController.java
  src/main/java/com/fesi/mukitlist/api/controller/auth/UserController.java
  src/main/java/com/fesi/mukitlist/api/controller/auth/request/UserCreateRequest.java
  src/main/java/com/fesi/mukitlist/api/controller/oauth/KakaoAuthApi.java
  src/main/java/com/fesi/mukitlist/api/controller/oauth/KakaoUserApi.java
  src/main/java/com/fesi/mukitlist/api/controller/oauth/kakao/KakaoTokenController.java
  src/main/java/com/fesi/mukitlist/api/controller/oauth/util/GsonLocalDateTimeAdapter.java
  src/main/java/com/fesi/mukitlist/api/exception/ExceptionCode.java
  src/main/java/com/fesi/mukitlist/api/repository/ReviewRepository.java
  src/main/java/com/fesi/mukitlist/api/repository/review/ReviewRepository.java
  src/main/java/com/fesi/mukitlist/api/service/auth/AuthenticationService.java
  src/main/java/com/fesi/mukitlist/api/service/auth/UserService.java
  src/main/java/com/fesi/mukitlist/api/service/auth/request/UserServiceCreateRequest.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/KakaoLoginService.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/LoginService.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/PrincipalOauthUserService.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/SocialLoginController.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/SocialLoginService.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/request/KakaoSocialLoginRequest.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/request/KakaoUserCreateRequest.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/response/KaKaoLoginResponse.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/response/LoginResponse.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/response/SocialAuthResponse.java
  src/main/java/com/fesi/mukitlist/api/service/oauth/response/SocialUserResponse.java
  src/main/java/com/fesi/mukitlist/config/FeignConfig.java
  src/main/java/com/fesi/mukitlist/config/JpaAuditingConfig.java
  src/main/java/com/fesi/mukitlist/domain/auth/User.java
  src/main/java/com/fesi/mukitlist/domain/auth/constant/GrantType.java
  src/main/java/com/fesi/mukitlist/domain/auth/constant/UserType.java
  src/main/resources/application.yml
  src/test/java/com/fesi/mukitlist/MukitlistApplicationTests.java
  src/test/java/com/fesi/mukitlist/api/repository/user/UserRegistrationTests.java
Labels: enhancement

#42 prod 환경 로깅 시스템 구현
  src/main/java/com/fesi/mukitlist/logging/LogTraceAspect.java
  src/main/java/com/fesi/mukitlist/logging/trace/LogTrace.java
  src/main/java/com/fesi/mukitlist/logging/trace/ThreadLocalLogTrace.java
  src/main/java/com/fesi/mukitlist/logging/trace/TraceId.java
  src/main/java/com/fesi/mukitlist/logging/trace/TraceStatus.java
Labels: enhancement

#50 Feature/#49 fe requirements
  build.gradle
  src/main/java/com/fesi/mukitlist/api/controller/auth/AuthenticationController.java
  src/main/java/com/fesi/mukitlist/api/controller/gathering/GatheringController.java
  src/main/java/com/fesi/mukitlist/api/controller/gathering/request/ChangeGatheringStautsRequest.java
  src/main/java/com/fesi/mukitlist/api/controller/gathering/request/GatheringUpdateRequest.java
  src/main/java/com/fesi/mukitlist/api/controller/mypage/MyPageController.java
  src/main/java/com/fesi/mukitlist/api/controller/mypage/response/MyPageReviewResponse.java
  src/main/java/com/fesi/mukitlist/api/controller/mypage/response/ReviewCompletedList.java
  src/main/java/com/fesi/mukitlist/api/controller/mypage/response/ReviewUnCompletedList.java
  src/main/java/com/fesi/mukitlist/api/exception/ExceptionCode.java
  src/main/java/com/fesi/mukitlist/core/gathering/Gathering.java
  src/main/java/com/fesi/mukitlist/core/repository/FavoriteGatheringRepository.java
  src/main/java/com/fesi/mukitlist/core/repository/gathering/GatheringRepository.java
  src/main/java/com/fesi/mukitlist/core/repository/review/ReviewRepository.java
  src/main/java/com/fesi/mukitlist/domain/service/auth/application/UserService.java
  src/main/java/com/fesi/mukitlist/domain/service/gathering/GatheringService.java
  src/main/java/com/fesi/mukitlist/domain/service/gathering/ParticipationService.java
  src/main/java/com/fesi/mukitlist/domain/service/gathering/request/GatheringServiceCreateRequest.java
  src/main/java/com/fesi/mukitlist/domain/service/gathering/request/GatheringServiceUpdateRequest.java
  src/main/java/com/fesi/mukitlist/domain/service/mypage/MyPageService.java
  src/main/java/com/fesi/mukitlist/domain/service/review/ReviewService.java
Labels: enhancement
